/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#e2e2e2",
        "on-primary-container": "#fffeff",
        "on-secondary-fixed-variant": "#004f54",
        "on-tertiary-fixed": "#3f0019",
        "secondary-fixed-dim": "#00dbe9",
        "tertiary": "#ffb1c3",
        "secondary": "#d3fbff",
        "tertiary-fixed": "#ffd9e0",
        "surface-dim": "#131313",
        "surface-tint": "#ebb2ff",
        "secondary-container": "#00eefc",
        "secondary-fixed": "#7df4ff",
        "on-secondary": "#00363a",
        "surface-container-highest": "#353535",
        "on-tertiary-fixed-variant": "#8f0041",
        "on-primary-fixed-variant": "#74009f",
        "surface-bright": "#393939",
        "on-background": "#e2e2e2",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#2a2a2a",
        "inverse-primary": "#9800d0",
        "tertiary-container": "#e6006d",
        "primary-container": "#bc00ff",
        "on-error": "#690005",
        "surface": "#131313",
        "on-tertiary-container": "#fffeff",
        "primary-fixed": "#f8d8ff",
        "on-primary-fixed": "#320047",
        "on-secondary-container": "#00686f",
        "background": "#131313",
        "primary": "#ebb2ff",
        "surface-variant": "#353535",
        "inverse-surface": "#e2e2e2",
        "error": "#ffb4ab",
        "outline-variant": "#504255",
        "inverse-on-surface": "#303030",
        "on-tertiary": "#66002c",
        "tertiary-fixed-dim": "#ffb1c3",
        "outline": "#9d8ba0",
        "primary-fixed-dim": "#ebb2ff",
        "surface-container-lowest": "#0e0e0e",
        "error-container": "#93000a",
        "on-primary": "#520071",
        "surface-container": "#1f1f1f",
        "surface-container-low": "#1b1b1b",
        "on-surface-variant": "#d4c0d7",
        "on-secondary-fixed": "#002022"
      },
      fontFamily: {
        "space": ["Space Grotesk", "sans-serif"],
        "vietnam": ["Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["4.5rem", { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["2.5rem", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["1.5rem", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["0.75rem", { lineHeight: "1.0", letterSpacing: "0.2em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
